comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
coverage:
  precision: 2
  round: up
  range: 70...100
  status:
    project:
      default:
        target: 75%
        threshold: 5%
      dev:
        paths:
          - .storybook/
          - mocks/
        target: 100%
        threshold: 5%
      components:
        paths:
          - src/components/
        target: 70%
        threshold: 5%
      utils:
        paths:
          - src/hooks/
          - src/utils.js
        target: 80%
        threshold: 5%
