name: Cut beta release
on: workflow_dispatch
jobs:
  createReleasePR:
    name: Create PR for release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_BRANCH: "release/beta"

    steps:
      # Setup release branch
      - uses: peterjgrainger/action-create-branch@v3
        with:
          branch: refs/heads/${{ env.RELEASE_BRANCH }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.RELEASE_BRANCH }}

      # Push commit from release-it: version bump, changelog, build
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm ci
      - run: npm run version-release:beta

      # Create the release PR
      - run: |
          gh pr create --base "beta" --head "${{ env.RELEASE_BRANCH }}" --label "release" --title "chore(release): publish beta" --body "🤖 **Preparing to release as [beta]**"
